module(
    name = "parallel_phylogenetic_inference",
    version = "0.1.0",
)

bazel_dep(name = "rules_cc", version = "0.2.17")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_cuda", version = "0.3.0")
bazel_dep(name = "rules_shell", version = "0.8.0")
bazel_dep(name = "bidirectional_tree_rake_compress", version = "0.1.0")
bazel_dep(name = "parallel_tree_hmm", version = "0.1.0")

accelerator_sdks = use_extension(
    "@parallel_tree_hmm//toolchains:extensions.bzl",
    "accelerator_sdks",
)
use_repo(accelerator_sdks, "cuda", "rocm_sdk")

beagle = use_extension("//third_party/beagle:extension.bzl", "beagle")
use_repo(beagle, "beagle")

git_override(
    module_name = "bidirectional_tree_rake_compress",
    commit = "36cfd7592a653011ac36ffd8e3d918acc59a2e05",
    remote = "https://github.com/joaospinto/bidirectional_tree_rake_compress.git",
)
git_override(
    module_name = "parallel_tree_hmm",
    commit = "af7cc473a21451a86c3b868f9525d5210c9b60e8",
    remote = "https://github.com/joaospinto/parallel_tree_hmm.git",
)
