#ifndef PARALLEL_PHYLOGENETICS_CUDA_H_
#define PARALLEL_PHYLOGENETICS_CUDA_H_

#define PARALLEL_PHYLOGENETICS_GPU_NAMESPACE cuda
#include "parallel_phylogenetics/detail/gpu_backend_api.inc"
#undef PARALLEL_PHYLOGENETICS_GPU_NAMESPACE

#endif // PARALLEL_PHYLOGENETICS_CUDA_H_
