#include "parallel_phylogenetics/cuda.h"

#include "tree_hmm/cuda.h"

#define PARALLEL_PHYLOGENETICS_GPU_NAMESPACE cuda
#define PARALLEL_PHYLOGENETICS_TREE_HMM_NAMESPACE cuda
#define PARALLEL_PHYLOGENETICS_GPU_NAME "CUDA"
#define PARALLEL_PHYLOGENETICS_GPU_HAS_DEVICE_SELECTION 1
#include "src/gpu_backend_impl.inc"
#undef PARALLEL_PHYLOGENETICS_GPU_HAS_DEVICE_SELECTION
#undef PARALLEL_PHYLOGENETICS_GPU_NAME
#undef PARALLEL_PHYLOGENETICS_TREE_HMM_NAMESPACE
#undef PARALLEL_PHYLOGENETICS_GPU_NAMESPACE
