#include "parallel_phylogenetics/metal.h"

#include "tree_hmm/metal.h"

#define PARALLEL_PHYLOGENETICS_GPU_NAMESPACE metal
#define PARALLEL_PHYLOGENETICS_TREE_HMM_NAMESPACE metal
#define PARALLEL_PHYLOGENETICS_GPU_NAME "Metal"
#define PARALLEL_PHYLOGENETICS_GPU_HAS_DEVICE_SELECTION 0
#include "src/gpu_backend_impl.inc"
#undef PARALLEL_PHYLOGENETICS_GPU_HAS_DEVICE_SELECTION
#undef PARALLEL_PHYLOGENETICS_GPU_NAME
#undef PARALLEL_PHYLOGENETICS_TREE_HMM_NAMESPACE
#undef PARALLEL_PHYLOGENETICS_GPU_NAMESPACE
